version: "3"
 
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kombiworld
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./src/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306